# Adeptus Astartes btop theme
# Cogitator Telemetry

theme[main_bg]="#0E121B"
theme[main_fg]="#E2DFD2"
theme[title]="#E5B53B"
theme[hi_fg]="#2563EB"
theme[selected_bg]="#242E42"
theme[selected_fg]="#F9FAFB"
theme[inactive_fg]="#4B5563"
theme[proc_misc]="#38BDF8"

theme[cpu_box]="#E5B53B"
theme[mem_box]="#2563EB"
theme[net_box]="#38BDF8"
theme[proc_box]="#4B5563"
theme[div_line]="#242E42"

theme[temp_start]="#10B981"
theme[temp_mid]="#E5B53B"
theme[temp_end]="#C41E3A"

theme[cpu_start]="#2563EB"
theme[cpu_mid]="#E5B53B"
theme[cpu_end]="#C41E3A"

theme[free_start]="#10B981"
theme[free_mid]="#34D399"
theme[free_end]="#E5B53B"

theme[cached_start]="#2563EB"
theme[cached_mid]="#3B82F6"
theme[cached_end]="#38BDF8"

theme[available_start]="#10B981"
theme[available_mid]="#34D399"
theme[available_end]="#E5B53B"

theme[used_start]="#2563EB"
theme[used_mid]="#E5B53B"
theme[used_end]="#C41E3A"

theme[download_start]="#2563EB"
theme[download_mid]="#38BDF8"
theme[download_end]="#E5B53B"

theme[upload_start]="#E5B53B"
theme[upload_mid]="#FBBF24"
theme[upload_end]="#C41E3A"

theme[process_start]="#2563EB"
theme[process_mid]="#E5B53B"
theme[process_end]="#C41E3A"
