$color = rgba(14, 18, 27, 1)
$inner_color = rgba(14, 18, 27, 0.75)
$outer_color = rgba(229, 181, 59, 1)
$font_color = rgba(226, 223, 210, 1)
$placeholder_color = rgba(156, 163, 175, 0.7)
$check_color = rgba(37, 99, 235, 1)
